version: "3.7"

services:
  carlemany-backend:
    build:
      context: .
      target: carlemany-backend-base
    image: carlemany-backend-base:latest  # add this to tag the image
    volumes:
      - type: bind
        source: .
        target: /carlemany-backend
    ports:
      - "8000:80"
    env_file:
      - .env
    networks:
      - carlemany-net

  black:
    build:
      context: .
      target: carlemany-backend-dev
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
        read_only: true
    entrypoint: sh -c "black --config .black --check --diff ."

  format:
    build:
      context: .
      target: carlemany-backend-dev
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
    entrypoint: sh -c "black --config .black . && ruff check --fix ."

  test: &test
    build:
      context: .
      target: carlemany-backend-dev
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
    networks:
      - carlemany-net
    entrypoint: pytest --maxfail=10

  test-cov:
    <<: *test
    entrypoint: pytest --maxfail=10 --cov --cov-report=term --cov-report=html --junitxml=tests/test-results/junit.xml

networks:
  carlemany-net: