
services:
  postgres:
    image: postgres:13.4-alpine3.14
    environment:
      - POSTGRES_DB=${PSQL_DB_DATABASE}
      - POSTGRES_USER=${PSQL_DB_USERNAME}
      - POSTGRES_PASSWORD=${PSQL_DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - type: volume
        source: carlemany-backend-data
        target: /var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d ${PSQL_DB_DATABASE} -U ${PSQL_DB_USERNAME}
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - carlemany-net

  carlemany-backend:
    build:
      context: .
      target: carlemany-backend-base
      #change to dev to see more logs
      #target: carlemany-backend-dev
    image: carlemany-backend-base:latest  # add this to tag the image
    volumes:
      - type: bind
        source: .
        target: /carlemany-backend
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - carlemany-net

  # Migration services
  make_migrations:
    build:
      context: .
      target: carlemany-backend-base
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /carlemany-backend
    networks:
      - carlemany-net
    depends_on:
      - postgres
    entrypoint: aerich migrate

  migrate:
    build:
      context: .
      target: carlemany-backend-base
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /carlemany-backend
    networks:
      - carlemany-net
    depends_on:
      - postgres
    entrypoint: aerich upgrade

  init_db:
    build:
      context: .
      target: carlemany-backend-base
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /carlemany-backend
    networks:
      - carlemany-net
    # this makes that before initialize init_db it is need to execute postgres
    depends_on:
      - postgres
    entrypoint: sh infra/init_db.sh

  black:
    build:
      context: .
      target: carlemany-backend-dev
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
        read_only: true
    entrypoint: sh -c "black --config .black --check --diff ."

  format:
    build:
      context: .
      target: carlemany-backend-dev
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
    entrypoint: sh -c "black --config .black . && ruff check --fix ."

  test: &test
    build:
      context: .
      target: carlemany-backend-dev
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
    networks:
      - carlemany-net
    entrypoint: pytest --maxfail=10

  test-cov:
    <<: *test
    entrypoint: pytest --maxfail=10 --cov --cov-report=term --cov-report=html --junitxml=tests/test-results/junit.xml

networks:
  carlemany-net:

volumes:
  carlemany-backend-data:
  postgres_data: